name: CI

on: [push, pull_request]

jobs:
  run_tests:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      # allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[test]

      - name: Running tests with pytest
        run: pytest -v

  additional_metrics:
    timeout-minutes: 5
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install package and dependencies
        run: |
          pip install --upgrade pip setuptools wheel --user
          pip install .[test]

      - name: Check the code with pycodestyle
        run: pycodestyle -v .

      - name: Type check the code with mypy
        if: ${{ always() }}
        run: mypy . --config-file mypy.ini --exclude build
